CREATE TABLE users (
    username VARCHAR2(50) PRIMARY KEY,
    password VARCHAR2(100)
);

CREATE SEQUENCE user_sequence
  START WITH 2
  INCREMENT BY 2
  NOCACHE
  NOCYCLE;

CREATE TABLE planner (
    planner_id VARCHAR2(10),
    name       VARCHAR2(100) NOT NULL,
    e_mail     VARCHAR2(100) NOT NULL,
    contact_no VARCHAR2(15)  NOT NULL
);

CREATE OR REPLACE VIEW planner_view AS
SELECT planner_id, name, e_mail, contact_no
FROM planner;

CREATE SEQUENCE planner_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

  CREATE TABLE MENU (
    MENU_ID VARCHAR2(10) PRIMARY KEY,
    MENU_COURSE VARCHAR2(100),
    CUISINE VARCHAR2(50)
);

CREATE OR REPLACE VIEW Menu_view AS
SELECT MENU_ID, MENU_COURSE, CUISINE
FROM MENU;

CREATE SEQUENCE MENU_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE TABLE booking (
    booking_id    VARCHAR2(10),
    booking_date  DATE NOT NULL,
    booking_type  VARCHAR2(50) NOT NULL
);

CREATE OR REPLACE VIEW Booking_view ASSELECT BOOKING_ID, 
TO_CHAR(BOOKING_DATE, 'YYYY-MM-DD') AS BOOKING_DATE,
 BOOKING_TYPE
FROM BOOKING;

CREATE SEQUENCE booking_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;



 
CREATE TABLE payment (
    payment_id  VARCHAR2(10),
    pdate       DATE NOT NULL,
    amount      NUMBER(10, 2) NOT NULL
);

CREATE VIEW payment_view AS
SELECT 
    AMOUNT,
    PDATE,
    PAYMENT_ID
FROM 
    PAYMENT;

CREATE SEQUENCE payment_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
